name: Sync Fork

on:
  schedule:
    - cron: '*/1 * * * *' # every 30 minutes

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          token: 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
          owner: KingRan
          base: master
          head: master
